//! Parses src/traits.rs and generates $OUT_DIR/generated_delegation.rs.
//! The generated code is include!'d at the end of lib.rs.
//!
//! src/traits.rs をパースして $OUT_DIR/generated_delegation.rs を生成する。
//! 生成コードは lib.rs 末尾で include! される。
//!
//! How it works / 仕組み:
//!   - "Trait" suffix (e.g. SolidTrait → crate::Solid): generates `impl crate::Solid { pub fn ... }`
//!   - "Module" suffix (e.g. IoModule → mod io): generates `pub mod io { pub fn ... }`
//!
//!   "Trait" → 具象型のinherent implを生成。"Module" → pub modを生成。
//!
//! Called from / 呼び出し元:
//!   build.rs: build_delegation(include_str!("src/traits.rs"), &out_dir)

use std::path::Path;

enum DelegationKind {
	/// FooTrait → impl crate::Foo { pub fn ... { <Self as FooTrait>::... } }
	InherentImpl { concrete_type: String },
	/// FooModule → pub mod foo { pub fn ... { <crate::Foo as FooModule>::... } }
	ModBlock {
		mod_name: String,
		struct_path: String,
	},
}

fn delegation_kind(trait_name: &str) -> DelegationKind {
	if trait_name.ends_with("Trait") {
		let type_name = &trait_name[..trait_name.len() - 5];
		DelegationKind::InherentImpl {
			concrete_type: format!("crate::{}", type_name),
		}
	} else if trait_name.ends_with("Module") {
		let base = &trait_name[..trait_name.len() - 6];
		let mod_name = base[..1].to_lowercase() + &base[1..];
		DelegationKind::ModBlock {
			mod_name,
			struct_path: format!("crate::{}", base),
		}
	} else {
		panic!(
			"build_delegation: trait '{}' must end with 'Trait' or 'Module'.",
			trait_name
		);
	}
}

/// Type replacements: only associated types need resolving.
/// Short names (DVec3, Mesh, Error, Color) are already in scope via pub use in lib.rs.
const TYPE_MAP: &[(&str, &str)] = &[("Self::Face", "Face"), ("Self::Edge", "Edge")];

struct Method {
	cfg: Option<String>,
	signature: String,
	name: String,
	args: Vec<String>,
	has_self: bool,
}

pub fn build_delegation(traits_src: &str, out_dir: &Path) {
	let mut output = String::new();
	output.push_str("// Auto-generated by build_delegation.rs — do not edit.\n\n");

	let traits = parse_traits(traits_src);

	for (trait_name, methods) in &traits {
		let kind = delegation_kind(trait_name);
		let trait_path = format!("crate::traits::{}", trait_name);

		match &kind {
			DelegationKind::InherentImpl { concrete_type } => {
				output.push_str(&format!("impl {} {{\n", concrete_type));
				for method in methods {
					if let Some(cfg) = &method.cfg {
						output.push_str(&format!("    {}\n", cfg));
					}
					let sig = resolve_types(&method.signature, concrete_type);
					output.push_str(&format!("    pub {}", sig));
					output.push_str(" {\n");
					let args_str = method.args.join(", ");
					if method.has_self {
						output.push_str(&format!(
							"        <Self as {}>::{}(self, {})\n",
							trait_path, method.name, args_str
						));
					} else {
						output.push_str(&format!(
							"        <Self as {}>::{}({})\n",
							trait_path, method.name, args_str
						));
					}
					output.push_str("    }\n");
				}
				output.push_str("}\n\n");
			}
			DelegationKind::ModBlock {
				mod_name,
				struct_path,
			} => {
				output.push_str(&format!("pub mod {} {{\n", mod_name));
				output.push_str("    use super::*;\n");
				for method in methods {
					if let Some(cfg) = &method.cfg {
						output.push_str(&format!("    {}\n", cfg));
					}
					let sig = resolve_types(&method.signature, struct_path);
					output.push_str(&format!("    pub {}", sig));
					output.push_str(" {\n");
					let args_str = method.args.join(", ");
					output.push_str(&format!(
						"        <{} as {}>::{}({})\n",
						struct_path, trait_path, method.name, args_str
					));
					output.push_str("    }\n");
				}
				output.push_str("}\n\n");
			}
		}
	}

	let out_path = out_dir.join("generated_delegation.rs");
	std::fs::write(&out_path, output).expect("Failed to write generated_delegation.rs");
}

/// Replace short type names and `Self` with fully-qualified paths.
fn resolve_types(sig: &str, concrete_type: &str) -> String {
	let mut s = sig.to_string();
	for (from, to) in TYPE_MAP {
		s = replace_type_word(&s, from, to);
	}
	s = replace_self_type(&s, concrete_type);
	s
}

/// Replace whole-word occurrences of `from` with `to` in type positions.
fn replace_type_word(sig: &str, from: &str, to: &str) -> String {
	let mut result = String::new();
	let bytes = sig.as_bytes();
	let from_bytes = from.as_bytes();
	let from_len = from_bytes.len();
	let mut i = 0;
	while i < bytes.len() {
		if i + from_len <= bytes.len() && &sig[i..i + from_len] == from {
			let before_ok = i == 0 || !is_ident_char(bytes[i - 1]);
			let after_ok = i + from_len >= bytes.len() || !is_ident_char(bytes[i + from_len]);
			if before_ok && after_ok {
				result.push_str(to);
				i += from_len;
				continue;
			}
		}
		result.push(bytes[i] as char);
		i += 1;
	}
	result
}

fn is_ident_char(b: u8) -> bool {
	b.is_ascii_alphanumeric() || b == b'_'
}

/// Replace `Self` as a type (not `self` as a parameter) with the concrete type.
fn replace_self_type(sig: &str, concrete_type: &str) -> String {
	let mut result = String::new();
	let bytes = sig.as_bytes();
	let mut i = 0;
	while i < bytes.len() {
		if i + 4 <= bytes.len() && &sig[i..i + 4] == "Self" {
			// Check it's not `self` (lowercase)
			let before_ok = i == 0 || !bytes[i - 1].is_ascii_alphanumeric();
			let after_ok = i + 4 >= bytes.len() || !bytes[i + 4].is_ascii_alphanumeric();
			if before_ok && after_ok {
				result.push_str(concrete_type);
				i += 4;
				continue;
			}
		}
		result.push(bytes[i] as char);
		i += 1;
	}
	result
}

/// Parse trait definitions from traits.rs source.
/// Returns vec of (trait_name, methods).
fn parse_traits(src: &str) -> Vec<(String, Vec<Method>)> {
	let mut traits = Vec::new();
	let lines: Vec<&str> = src.lines().collect();
	let mut i = 0;

	while i < lines.len() {
		let line = lines[i].trim();

		// Look for trait definition
		if line.contains("trait ") && line.contains('{') {
			let trait_name = extract_trait_name(line);
			if let Some(name) = trait_name {
				let mut methods = Vec::new();
				i += 1;

				let mut pending_cfg: Option<String> = None;
				while i < lines.len() {
					let line = lines[i].trim();

					if line == "}" {
						break;
					}

					// Collect #[cfg(...)] attributes
					if line.starts_with("#[cfg(") {
						pending_cfg = Some(line.to_string());
						i += 1;
						continue;
					}

					// Skip associated type declarations
					if line.starts_with("type ") {
						i += 1;
						continue;
					}

					// Skip comments and empty lines
					if line.starts_with("//") || line.is_empty() {
						i += 1;
						continue;
					}

					// Parse fn signature
					if line.starts_with("fn ") {
						if let Some(method) = parse_method(line, pending_cfg.take()) {
							methods.push(method);
						}
					} else {
						pending_cfg = None;
					}

					i += 1;
				}

				traits.push((name, methods));
			}
		}
		i += 1;
	}
	traits
}

fn extract_trait_name(line: &str) -> Option<String> {
	// "pub trait SolidTrait: Sized + Clone {"
	// "pub(crate) trait SolidTrait: Sized + Clone {"
	let idx = line.find("trait ")?;
	let rest = &line[idx + 6..];
	let end = rest.find(|c: char| c == ':' || c == '{' || c == ' ')?;
	Some(rest[..end].trim().to_string())
}

fn parse_method(line: &str, cfg: Option<String>) -> Option<Method> {
	// "fn name(args) -> RetType;"
	let line = line.trim().trim_end_matches(';');

	let fn_idx = line.find("fn ")?;
	let rest = &line[fn_idx + 3..];

	let paren_open = rest.find('(')?;
	let name_with_generics = rest[..paren_open].trim();
	let name = if let Some(angle) = name_with_generics.find('<') {
		name_with_generics[..angle].trim().to_string()
	} else {
		name_with_generics.to_string()
	};

	let paren_close = rest.rfind(')')?;
	let args_str = &rest[paren_open + 1..paren_close];

	// Determine if method has self parameter, and collect non-self arg names
	let mut has_self = false;
	let mut args = Vec::new();

	for arg in split_args(args_str) {
		let arg = arg.trim();
		if arg.is_empty() {
			continue;
		}
		if arg == "self" || arg == "&self" || arg == "mut self" || arg == "&mut self" {
			has_self = true;
			continue;
		}
		// "name: Type" -> extract name
		if let Some(colon) = arg.find(':') {
			let arg_name = arg[..colon].trim().to_string();
			args.push(arg_name);
		}
	}

	// Reconstruct signature: "fn name(self/&self, args) -> RetType"
	let signature = line[fn_idx..].to_string();

	Some(Method {
		cfg,
		signature,
		name,
		args,
		has_self,
	})
}

/// Split arguments by ',' while respecting `<>` nesting.
fn split_args(s: &str) -> Vec<&str> {
	let mut result = Vec::new();
	let mut depth = 0usize;
	let mut start = 0;
	for (i, b) in s.bytes().enumerate() {
		match b {
			b'<' => depth += 1,
			b'>' => {
				if depth > 0 {
					depth -= 1;
				}
			}
			b',' if depth == 0 => {
				result.push(&s[start..i]);
				start = i + 1;
			}
			_ => {}
		}
	}
	result.push(&s[start..]);
	result
}
